"""
LangGraph Evidence-First Agentic AI workflow for ValueAI.

Architecture:

    User Question
          |
          v
    Evidence Router
          |
          v
    Verified Analytical Tool
          |
          v
    Evidence Package
          |
          v
    Qwen 2.5 7B
          |
          v
    Executive Business Response

The analytical evidence is retrieved deterministically before the LLM
generates the response. This prevents the LLM from inventing
quantitative analytical evidence.
"""

from __future__ import annotations

import json
import re
from typing import Any, TypedDict

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_ollama import ChatOllama
from langgraph.graph import END, START, StateGraph

from src.ai_agent.agent_tools import (
    analyze_high_risk_cluster,
    get_shap_feature_importance,
    get_model_metadata,
    predict_readmission_risk,
)


# ---------------------------------------------------------------------------
# MODEL CONFIGURATION
# ---------------------------------------------------------------------------

llm = ChatOllama(
    model="qwen2.5:7b",
    temperature=0.0,
)


# ---------------------------------------------------------------------------
# ANALYTICAL TOOLS
# ---------------------------------------------------------------------------

tools = [
    analyze_high_risk_cluster,
    get_shap_feature_importance,
    get_model_metadata,
    predict_readmission_risk,
]


# ---------------------------------------------------------------------------
# SYSTEM INSTRUCTIONS
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """
You are the ValueAI Data Science Assistant.

You are an analytical decision-support assistant for healthcare
business stakeholders.

Your role is to interpret VERIFIED evidence from Phase 2 analytical
artifacts and convert it into concise, executive-level business insight.

You are NOT a clinician and must not diagnose or prescribe treatment.

============================================================
EVIDENCE-FIRST ARCHITECTURE
============================================================

The application has already retrieved the relevant analytical evidence
before you receive this request.

The section labelled:

VERIFIED ANALYTICAL EVIDENCE

is authoritative for quantitative claims.

You MUST use the supplied evidence.

You MUST NOT invent, estimate, reconstruct, approximate, substitute,
or alter numerical values.

You MUST NOT introduce quantitative values that are absent from the
verified evidence.

If the evidence does not establish something, explicitly say so.

============================================================
EVIDENCE CATEGORIES
============================================================

Always distinguish:

1. OBSERVED DATA

Descriptive statistics calculated directly from the dataset.

2. MODEL IMPORTANCE

SHAP feature-importance results describing how strongly features
contribute to model predictions.

3. MODEL PREDICTION

A probability or class generated by the trained prediction model.

4. CAUSAL EVIDENCE

Evidence demonstrating that changing one variable causes an outcome.

These are NOT interchangeable.

In particular:

SHAP IMPORTANCE ≠ DIRECTIONAL EFFECT ≠ CAUSATION.

============================================================
NUMERICAL INTEGRITY
============================================================

Every numerical statement in the final answer must be supported by
the VERIFIED ANALYTICAL EVIDENCE.

Do not:

- invent patient counts
- invent percentages
- invent averages
- invent SHAP values
- invent model metrics
- invent prediction probabilities
- invent financial values
- invent statistical results
- invent dataset characteristics

Do not round or alter a value in a way that changes its meaning.

When reporting values, use sensible executive-level rounding while
remaining faithful to the supplied evidence.

============================================================
HIGH-RISK CLUSTER
============================================================

The high-risk cluster is Cluster 2 according to the Phase 2 patient
segmentation analysis.

When the evidence contains high-risk cluster information:

- describe Cluster 2 as a segmentation/clustering result;
- describe its population and utilization characteristics as
  observed/descriptive data;
- do not describe the cluster as being created by the readmission
  classification model;
- do not transform descriptive statistics into causal claims.

============================================================
SHAP INTERPRETATION
============================================================

The current SHAP artifact contains MEAN ABSOLUTE SHAP VALUES.

Mean absolute SHAP measures the average magnitude of a feature's
contribution to model predictions.

It provides feature importance/ranking.

It does NOT provide direction.

Therefore, never claim that:

- higher values increase readmission;
- lower values increase readmission;
- higher values decrease readmission;
- lower values decrease readmission;

unless directional evidence is explicitly supplied.

Never claim that a SHAP-ranked feature causes readmission.

When reporting SHAP drivers, use the exact feature names, ranks,
and mean absolute SHAP values supplied in the evidence.

Always make clear that:

"Mean absolute SHAP importance describes contribution magnitude,
not direction or causation."

============================================================
RECOMMENDATION RULES
============================================================

Recommendations are proposed business interventions or hypotheses
for evaluation.

They are NOT guaranteed outcomes.

Never say an intervention WILL:

- reduce readmissions;
- reduce costs;
- reduce length of stay;
- reduce utilization;
- improve outcomes;
- generate savings;
- generate ROI.

Use language such as:

- "could be evaluated"
- "could be tested"
- "may help"
- "a proposed intervention is"
- "the business could pilot"
- "effectiveness should be measured"

Do not recommend directly manipulating a SHAP feature merely because
it has a high SHAP ranking.

Instead, recommendations should address business or operational
processes reasonably connected to the observed evidence.

Examples include:

- targeted care-coordination workflows;
- structured post-discharge follow-up;
- complex-patient case-management;
- utilization review;
- admission/discharge process analysis;
- segmentation-based outreach;
- operational monitoring dashboards;
- targeted review of frequently admitted populations.

These are hypotheses for evaluation, not proven causal solutions.

Never invent:

- expected savings;
- percentage improvement;
- ROI;
- cost reduction;
- readmission reduction;
- financial return.

============================================================
RECOMMENDATION FORMAT
============================================================

When strategic recommendations are requested, provide exactly three.

For each recommendation provide:

Intervention:
What the business could do.

Evidence:
What verified dataset or model evidence supports considering it.

Value mechanism:
How the intervention could potentially create operational,
clinical, or financial value.

KPI:
What measurable outcome should be monitored.

============================================================
CLINICAL SAFETY
============================================================

This is an analytical decision-support prototype.

Do not:

- diagnose patients;
- prescribe medication;
- provide patient-specific treatment;
- fabricate clinical guidance.

============================================================
EXECUTIVE RESPONSE FORMAT
============================================================

For high-risk cluster, SHAP, readmission-driver, or strategic
business questions, use:

## EXECUTIVE SUMMARY

Give a concise summary of the most important verified findings.

## HIGH-RISK SEGMENT

Describe the high-risk cluster using verified observed data.

## KEY MODEL DRIVERS

List the relevant SHAP features and their exact mean absolute
SHAP values from the evidence.

State clearly that mean absolute SHAP does not establish whether
higher or lower values increase predicted risk.

## WHAT THE DATA SHOWS

Separate:

- observed cluster characteristics;
- model importance;
- model predictions, if available.

Do not mix these categories.

## STRATEGIC RECOMMENDATIONS

When requested, provide exactly three recommendations.

For each:

1. Intervention
2. Evidence
3. Value mechanism
4. KPI

## MODEL / DATA CAVEATS

Mention the relevant limitations, including:

- SHAP importance does not establish causation;
- mean absolute SHAP does not provide direction;
- cluster statistics are descriptive;
- recommendations are hypotheses for evaluation;
- model predictions are not clinical diagnoses.

============================================================
EXECUTIVE SUMMARY
============================================================

For strategic analytical questions, the response MUST begin with:

## EXECUTIVE SUMMARY

The Executive Summary must contain only verified findings.

============================================================
STYLE
============================================================

Be concise.

Write for healthcare business executives.

Prefer plain business language.

Avoid unnecessary machine-learning terminology.

When discussing SHAP, preserve the distinction between:

- importance;
- direction;
- prediction;
- causation.

Never manufacture evidence to make the answer sound complete.

============================================================
FINAL QUALITY CHECK
============================================================

Before producing the response verify:

- All quantitative claims come from VERIFIED ANALYTICAL EVIDENCE.
- No unsupported numbers were introduced.
- High-risk cluster is described as a segmentation result.
- Observed data is distinguished from model importance.
- Mean absolute SHAP is not treated as directional.
- No causal claims are made.
- Recommendations are presented as hypotheses for evaluation.
- No guaranteed business outcomes are claimed.
- Exactly three recommendations are provided when requested.
"""


# ---------------------------------------------------------------------------
# LANGGRAPH STATE
# ---------------------------------------------------------------------------

class AgentState(TypedDict, total=False):
    user_query: str
    evidence_source: str
    evidence: dict[str, Any]
    response: str


# ---------------------------------------------------------------------------
# QUERY CLASSIFICATION
# ---------------------------------------------------------------------------

def _normalise_query(query: str) -> str:
    """
    Normalize a user query for deterministic evidence routing.
    """

    return " ".join(
        query.lower().strip().split()
    )


def _contains_any(
    query: str,
    phrases: tuple[str, ...],
) -> bool:
    """
    Return True when any phrase appears in the normalized query.
    """

    return any(
        phrase in query
        for phrase in phrases
    )


def determine_evidence_source(
    user_query: str,
) -> str:
    """
    Determine which analytical evidence source is required.

    Routing is deterministic. The LLM does not decide whether
    quantitative evidence should be retrieved.
    """

    query = _normalise_query(
        user_query
    )

    # ------------------------------------------------------------
    # High-risk cluster
    # ------------------------------------------------------------

    high_risk_terms = (
        "high-risk cluster",
        "high risk cluster",
        "high-risk segment",
        "high risk segment",
        "cluster 2",
        "risk cluster",
        "high risk population",
        "high-risk population",
    )

    # High-risk questions take priority because the cluster tool
    # also contains the relevant SHAP evidence.
    if _contains_any(
        query,
        high_risk_terms,
    ):
        return "high_risk_cluster"

    # ------------------------------------------------------------
    # SHAP / model drivers
    # ------------------------------------------------------------

    shap_terms = (
        "shap",
        "model driver",
        "model drivers",
        "feature importance",
        "feature ranking",
        "readmission drivers",
        "readmission driver",
    )

    if _contains_any(
        query,
        shap_terms,
    ):
        return "shap"

    # ------------------------------------------------------------
    # Model metadata / performance
    # ------------------------------------------------------------

    metadata_terms = (
        "model performance",
        "model metrics",
        "auc",
        "auc-roc",
        "roc auc",
        "accuracy",
        "precision",
        "recall",
        "f1",
        "feature schema",
        "classification features",
        "model features",
    )

    if _contains_any(
        query,
        metadata_terms,
    ):
        return "model_metadata"

    # ------------------------------------------------------------
    # Individual prediction
    # ------------------------------------------------------------

    prediction_terms = (
        "predict readmission",
        "readmission probability",
        "readmission risk prediction",
        "patient prediction",
        "individual patient",
    )

    if _contains_any(
        query,
        prediction_terms,
    ):
        return "prediction"

    # ------------------------------------------------------------
    # Default
    # ------------------------------------------------------------

    return "none"


# ---------------------------------------------------------------------------
# PREDICTION INPUT EXTRACTION
# ---------------------------------------------------------------------------

def _extract_prediction_features(
    user_query: str,
) -> dict[str, Any] | None:
    """
    Extract a JSON object from a prediction request.

    The prediction tool requires explicit patient feature values.
    We never invent missing values.
    """

    matches = re.findall(
        r"\{.*\}",
        user_query,
        flags=re.DOTALL,
    )

    if not matches:
        return None

    candidate = matches[-1]

    try:

        parsed = json.loads(
            candidate
        )

    except json.JSONDecodeError:

        return None

    if not isinstance(
        parsed,
        dict,
    ):
        return None

    return parsed


# ---------------------------------------------------------------------------
# EVIDENCE RETRIEVAL
# ---------------------------------------------------------------------------

def retrieve_evidence(
    state: AgentState,
) -> AgentState:
    """
    Deterministically retrieve verified analytical evidence before
    the LLM is invoked.
    """

    user_query = state[
        "user_query"
    ]

    evidence_source = determine_evidence_source(
        user_query
    )

    # ------------------------------------------------------------
    # High-risk cluster evidence
    # ------------------------------------------------------------

    if evidence_source == "high_risk_cluster":

        raw_evidence = (
            analyze_high_risk_cluster.invoke({})
        )

        evidence = json.loads(
            raw_evidence
        )

        return {
            **state,
            "evidence_source": evidence_source,
            "evidence": evidence,
        }

    # ------------------------------------------------------------
    # SHAP evidence
    # ------------------------------------------------------------

    if evidence_source == "shap":

        raw_evidence = (
            get_shap_feature_importance.invoke({})
        )

        evidence = json.loads(
            raw_evidence
        )

        return {
            **state,
            "evidence_source": evidence_source,
            "evidence": evidence,
        }

    # ------------------------------------------------------------
    # Model metadata
    # ------------------------------------------------------------

    if evidence_source == "model_metadata":

        raw_evidence = (
            get_model_metadata.invoke({})
        )

        evidence = json.loads(
            raw_evidence
        )

        return {
            **state,
            "evidence_source": evidence_source,
            "evidence": evidence,
        }

    # ------------------------------------------------------------
    # Individual prediction
    # ------------------------------------------------------------

    if evidence_source == "prediction":

        features = _extract_prediction_features(
            user_query
        )

        if features is None:

            evidence = {
                "analysis_type": "Readmission prediction",
                "evidence_available": False,
                "reason": (
                    "The request appears to require an individual "
                    "readmission prediction, but explicit patient "
                    "feature values were not supplied as JSON."
                ),
            }

        else:

            raw_evidence = (
                predict_readmission_risk.invoke(
                    {
                        "patient_features_json": json.dumps(
                            features
                        )
                    }
                )
            )

            evidence = json.loads(
                raw_evidence
            )

        return {
            **state,
            "evidence_source": evidence_source,
            "evidence": evidence,
        }

    # ------------------------------------------------------------
    # No specialized evidence required
    # ------------------------------------------------------------

    evidence = {
        "analysis_type": "No specialized analytical evidence",
        "evidence_available": False,
        "reason": (
            "The question was not mapped to a specialized analytical "
            "artifact by the deterministic evidence router."
        ),
    }

    return {
        **state,
        "evidence_source": "none",
        "evidence": evidence,
    }


# ---------------------------------------------------------------------------
# RESPONSE GENERATION
# ---------------------------------------------------------------------------

def generate_response(
    state: AgentState,
) -> AgentState:
    """
    Generate the executive response using only the verified evidence
    retrieved by the previous graph node.
    """

    user_query = state[
        "user_query"
    ]

    evidence = state.get(
        "evidence",
        {},
    )

    evidence_source = state.get(
        "evidence_source",
        "none",
    )

    evidence_json = json.dumps(
        evidence,
        indent=2,
        ensure_ascii=False,
    )

    user_message = f"""
VERIFIED ANALYTICAL EVIDENCE
============================

Evidence source:
{evidence_source}

The following JSON was retrieved directly from the ValueAI
analytical artifacts before this response was generated.

Treat this evidence as authoritative.

{evidence_json}


USER QUESTION
=============

{user_query}


RESPONSE REQUIREMENTS
=====================

Answer the user's question using the verified evidence above.

Do not invent quantitative values.

Do not introduce numerical values that are absent from the evidence.

Do not alter the meaning of the evidence.

If the evidence does not establish something, explicitly say so.

Keep observed data, model importance, model predictions, and causal
evidence separate.

If the question concerns SHAP, remember that the supplied SHAP values
are mean absolute SHAP values and therefore provide importance magnitude,
not direction or causation.

If strategic recommendations are requested, provide proposed
interventions only and describe them as hypotheses for evaluation.

Never claim that an intervention will reduce readmissions, costs,
utilization, length of stay, or generate savings unless such evidence
is explicitly supplied.

When the question is a high-risk cluster or strategic business
question, follow the executive response structure in the system
instructions.
"""

    result = llm.invoke(
        [
            SystemMessage(
                content=SYSTEM_PROMPT
            ),
            HumanMessage(
                content=user_message
            ),
        ]
    )

    content = getattr(
        result,
        "content",
        None,
    )

    if not content:

        raise RuntimeError(
            "Qwen returned an empty response."
        )

    return {
        **state,
        "response": content,
    }


# ---------------------------------------------------------------------------
# LANGGRAPH WORKFLOW
# ---------------------------------------------------------------------------

workflow = StateGraph(
    AgentState
)

workflow.add_node(
    "retrieve_evidence",
    retrieve_evidence,
)

workflow.add_node(
    "generate_response",
    generate_response,
)

workflow.add_edge(
    START,
    "retrieve_evidence",
)

workflow.add_edge(
    "retrieve_evidence",
    "generate_response",
)

workflow.add_edge(
    "generate_response",
    END,
)

agent = workflow.compile()


# ---------------------------------------------------------------------------
# PUBLIC API
# ---------------------------------------------------------------------------

def invoke_agent(
    user_query: str,
) -> str:
    """
    Run the ValueAI evidence-first LangGraph workflow.

    Evidence retrieval happens before Qwen generation, ensuring that
    quantitative analytical claims are grounded in real Phase 2
    artifacts.
    """

    if not user_query or not user_query.strip():

        raise ValueError(
            "User query cannot be empty."
        )

    result = agent.invoke(
        {
            "user_query": user_query.strip(),
        }
    )

    response = result.get(
        "response"
    )

    if not response:

        raise RuntimeError(
            "Agent returned an empty final response."
        )

    return response